---
abstract: 'Simple Perl Version of mod_dir'
author:
  - 'David E. Wheeler <david@justatheory.com>'
build_requires:
  Module::Build: 0.2701
  Test::More: 0.17
configure_requires:
  Module::Build: 0.2701
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Apache-Dir
provides:
  Apache::Dir:
    file: lib/Apache/Dir.pm
    version: 0.07
recommends:
  Test::Pod: 1.41
  mod_perl: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.07
